

const linkRegex = /(f|)/i

export async function before(m, { conn, isAdmin, isBotAdmin, isOwner }) {
    if (m.isBaileys && m.fromMe)
        return !0
    if (!m.isGroup) return !1
    let chat = global.db.data.chats[m.chat]
    let bot = global.db.data.settings[this.user.jid] || {}
    const isGroupLink = linkRegex.exec(m.text)
   
    if (chat.fight && isGroupLink && isOwner){
    	m.reply('syntax ⚡')
    }
    else
    if (chat.fight && isGroupLink && !isOwner && !isBotAdmin){
m.reply(pickRandom(slang))
        }
        else
 if (chat.fight && isGroupLink && !isOwner && isBotAdmin){
//conn.sendMessage(m.chat, { delete: m.key })
m.reply(pickRandom(slang))
        }
    return true
}
/*Function*/
function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}
let slang = [
"TERI MA KI CHUT MARU",
"TERE GAND ME SALENSER DALU",
"TERI MA K CHUT K JUICE BECHU BAZAR ME",
"TERI RANDI MA ROAD PE CHALI APNI CHUT DIKHATE AND GAND ME ROAD DALE HUE",
"TERI MA K CHUT ME ELECTRIC SHOCK LAGA DU",
"BAHEN K LAVDE",
"TU APNI MA Q CHUDA RAHA HAI",
"TERI MA K CHUT PE THAPPAD MARU",
"KYA BE GB ROAD WALE RANDI KA BETA",
"AABB KYA TU APNI MA CHUDAYEGA YAHA",
"BAHENCHOD TERE BAAP HAI HAM",
"TERI RANDI MA K CHUT PE NIMBU NICHODU",
"BHAG JA BHOSADIKE",
"AABB 😜 TERI MA KALAP GAI KYA",
"TERI RANDI MA 😁😙 CHUD GAI",
"BAHENCHOD TERI MA 😬 KO CHOD DUNGA",
"TERI BAHEN K CHUT ME 🍼 LAVA DAAL DU",
"KYA 💩 BE CHHAKE",
"TERI BAHEN 😂 KO GANNE K KHET ME CHODU",
"APNI MA KO BHEJ NANGA 🥺🥵 KARKE GHUMAUNGA",
"RANDI K AULAD SALE",
"TERI GIRLFRIEND KO NANGA 🤧🤣 GHUMAUNGA",
"GB ROAD K RANDI TERI MA 😂",
"KYA BE CHHAKE KI AULAD",
"Sun Beta Teri Randi Ma Ko Maine Hi Oye me Choda Tha",
"Bahenchod Sala Bhadwa",
"Teri Ma K Chut me Hathi Ka Lund",
"Sale Gay Teri ma chud gai hai gbroad pe",
"Kya Be Teri Bahen k chut me garam Rod dalu",
"sale madherchod",
"Teri bahen ko chodu doted condom laga k",
"rape karunga teri bahen ka doted condom laga k",
'nagar palika teri maa ka bhosdka bhen choooddddd','madar chod bhosdke esa lagta h apne hii taaate kaat ke chipka diya apni shakal dekh lodee jese shakal aur gand me h aakal',' saali Chinaal ki gadde ki nipple ki baal ki joon','tere maa log ka boor yaha dhanda chal raha hai jo apna gaand marane ke liyae number de rahe ho… maderchod log jao apna gaand me gandhi ka laura lo or aandhi machalo apna gaand me…. boor bandar jaha dekha lund waha failate ho gand tumra gaand me juroshik park ka lund bhi jaye to kam hai… gaand hai ke kuwa hai randi ka ladka…','choot ke chaman','Teri maa ki chut bhosdi kay','Aawara ladke hi teri chut ka bhosda karenge Teri gaand marke','jhant ke dingar yaha kya apni bahan chuda raha hai ja apne bahan ki jhato me ghoomiye bosdibal randi ki najayj olad chal bhag bhosdi ke  ','KAMINE BHENCHOD BHOOTNIKE SAALE ERI MAA KI AANKH CHUTIYA BEHN KE LAND STRAW LAGAKE CHOOSLE APNI MAA KI GAND SE TATTI',
  "TERI MA KI CHUT MARU",
"BAHEN K LAVDE",
"TU APNI MA Q CHUDA RAHA HAI",
"TERI MA K CHUT PE THAPPAD MARU",
"KYA BE GB ROAD WALE RANDI KA BETA",
"AABB KYA TU APNI MA CHUDAYEGA YAHA",
"BAHENCHOD TERE BAAP HAI HAM",
"TERI RANDI MA K CHUT PE NIMBU NICHODU",
"BHAG JA BHOSADIKE",
"AABB 😜 TERI MA KALAP GAI KYA",
"TERI RANDI MA 😁😙 CHUD GAI",
"BAHENCHOD TERI MA 😬 KO CHOD DUNGA",
"TERI BAHEN K CHUT ME 🍼 LAVA DAAL DU",
"KYA 💩 BE CHHAKE",
"TERI BAHEN 😂 KO GANNE K KHET ME CHODU",
"APNI MA KO BHEJ NANGA 🥺🥵 KARKE GHUMAUNGA",
"RANDI K AULAD SALE",
"TERI GIRLFRIEND KO NANGA 🤧🤣 GHUMAUNGA",
"GB ROAD K RANDI TERI MA 😂",
"KYA BE CHHAKE KI AULAD",
"TERI MA KO CHODNEE MAZA AATA HAI 🥵",
"TERI AMMY KA CH00T KITNA 😂 CHHOTA HAI RE KAISE😂  BAHAR AYA TU ?",
"JB MAI TERI😂 AMMY KE GQND MEI 😂 LQND DALNE GYA TOH MERA 😂LQND HI MUD GYA",
"TERI AMMY BAHUT 😂JAANDAAR HAI SALI😂 CHILLAI TAK NAHI😂 JB MAINE USKE SATH ANQL KIYA",
" 4 ,4 C0ND0M.😂USE KIYA EK DIN 😂MEI TERI CHHOTI😂 BEHN PE",
" BUKHAR HOTE 😂 HUYE PELA TERI😂 BEHN KO",
"CHALTI SADAK😂 PE TERI AMMY KE MUH😂 MEI DE DETA 😂HUN MAI ",
"TERI BEHN JIS 😂HOSTLE MEI REHTI N 😂USKA ROJ DEEWAL 😂KUDATTA HUN MAI",
"TERI BEHN 😂MERE KACHHE KO APNA 😂 MASK SAMAJH KE PEHNTI HAI",
"BILLICH0DE SALE😂BAAP SE GQNDM@STI 😂KREGA TU",
"APNI BUA KO 😂SAMJHA DE WARNA 😂 😂AISA KEENCH KE THAPPAD MARUNGA M@R JAYEGI😂 SAALI BAHUT UCHHALTI",
"TERI  😂 AMMY KE BHOXDE 😂  MEI PUNCHING 😂  MACHINE SE PUNCH 😂  KR DUNGA",
" MPL KHEL  😂 KHEL KE TERI  😂 AMMY KO PELUNGA",
"BEEHAD KE  😂 PAHADO MEI LEJAKR  😂  TERE PURE KHANDAN SE 😂  R@NDI KAA NAACH KRWAUNGA",
"PARAGLIDING KRTE  😂 HUYE TERI WIFE KO  😂 PELUNGA KACHAKACH",
"MICKKY MAUSE  😂 KI CHHATI AULAAD  😂 BSD KE",
"TERE G@ND 😂 MEI JO CHHED HAI N 😂  USKO FAAD KE GUFA 😂 BANA DUNGA AUKAAD  😂 SE BAHAR GYA TOH",
"THANDI MEI AAG JALA 😂  KE USKE UPAR BED 😂  LAGA KE TERI  😂 BEHN KO CH0DUNGA",
"APNE JH@NT KA 😂  JUICE  PILAUNGA  😂 TERI  AMMY KO",
" TERI AMMY KO BELAN  😂 USE KRTE HUYE PAKDA 😂  THA MAINE EK DIN BOLTI HAI 😂  KYA KRU DILD0 KHARIDNE  😂 KA PAISA NI TOH MAI  😂 BOLA MERA SUDOL L@ND HAI N YE LO",
"CHHENI HATHORI  😂 SE TERI AMMY KA 😂  CH00T PHOD DUNGA",
"CRYPTO 😂 CURRENCY SE TERI😂 AMMY KO KHARID 😂 KE CH0DUNGA",
"CH00CHIDHARI 😂 NARI KE NAZAYAZ 😂 AULAAD",
"NANGA LETA😂 KE TUJHE TERE 😂 😂 G@ND PE BIKE KA SILENCER😂 DAAL DUNGA",
"KEKDA CHOR😂 DUNGA TERE BAAP KE G@ND😂 ME",
"BICHHU KE😂 DANK SE PAIDA😂 HUA CHACHUNDAR 😂HAI TU",
"APNE JH@NT KA 😂TABIJ BNA KE PEHNAUNGA 😂 TUJHE",
"TERI AMMY KE 😂 MOULIK ADHIKAR KI MA 😂 CH0D DUNGA",
"KHUNI BAWASIR😂 KE PAIDAIS BSD K",
"LACHATAHE 😂 M@DHAR CH0D",
"TERI GF KO SINGING KRNE 😂KA BAHUT SHOKH HAI DIN RAAT 😂 MERE MIC KO MUH ME LAGAI 😂 REHTI HAI",
"MADH3RXHOD 😂KI AULAD BH3NXHODI😂 XAL3 RANDI BHANGI😂 MADHERXHOD T3RI😂 MA KI KALI GAAND M3 😂LUND MARU B3H3N K3😂 L0WD3 SUWR K3 BACH3 😂T3RI MA KA BH0SDA😂 B3H3NCH0UD K3 😂BACH3 RANDII K3 DIN3 😂B3TICH0UD KI AUALD SADI GAAND VAL3 KUT3 K3 BACH3 B3H3NCH0UD 😂K3 DIN3 T3RI MA KI SADI 😂CH00T M3 LUND 😂MAR K3 USKA BH0SDA FADU😂 CH00T MARI😂 K3 GAANDV3 K3 BADCH3 😂B3H3NCH0UD K3 BACH3😂 B3TICH0UD KI AUALD T3RI MA 😂KI KALI CH00T T3RI MA K3😂 BH0SD3 M3 THPAD DUNGA😂 SAL3 GHANDV3 K3 BADCH3 😂B3H3NCH0UD K3 DIN3 T3RI MA😂 KI SADI CH00T MAI 😂GATR M3 DUB0 DUB0 K3 MARUNGA 😂KANJR K3 DIN3 B3H3NCH0UD😂 MA K3 LUND B3TICH0UD😂 K3 BACH3 T3RI MA K3 😂BH0SD3 K0 CH33R 😂K3 RKH DU SAL3 GAANDv3 😂T3RI MA KI GAAND M3 😂 😂SAND KA LULLA FASA😂 DU BH0SDI K3 DAL33T😂 K3 BACH3 T3RI MA K3 BH0SD3 😂M3 CURRNT LAGA K3 USK3 BHS0D3 😂 M3 S3 BACH3 PAIDA KAR 😂DUNGA MA K3 LUND T3RI B3H3N 😂 KI CH0TI",
"MATHRCHD K3 😂BACH3 CHUD3 😂HU3 TATT3 YHA 😂APNI MA K0 CHUDAN3 AYA THA MA K3 LUND T3RI😂 MA K3 BH0SD3 M3 APN3 LUND😂 S3 USK3 BH0SD3 K0 KHULA 😂KAR DUNGA SAL3 CHAMR CHINAL K3 PIL3 😂K0TH3 VALI RANDI K3 😂IKL0T3 KUTIYA K3 BACH3 B3H3NCH0UD😂 K3 DIN3 T3RI MA K3 KAL3 BH00SD3 😂M3 B0MB F0D K3 BLAST😂 KRVA DUNGA MATHRCHD K3 BACH3 CH00T😂 MARI K3 DIN3 T3RI B3H3N KA😂 RAP3 KARUNGA BHARI M3TR0 M3 L3 😂JA K3 MA K3 LUND SAL3 CHTIY3😂K3 BACH3 CHUDAKAD KH0R KI😂 AUALD HRAM K3 PIL3 M3RA L0WDA😂 CHOOS3GA T3RI MA KI GAAND M3 ITN3 😂L0WD3 MARUNGA USKI GAAND 😂L0D0 KI KHAN LAG3N3 LG3GI 😂B3H3NCH0UD MATHRCHD K3 😂BACH3 SUWR K3 BACH3 T3RI😂 MA KI GAAND M3 MUKK3 😂MAR K USKI GAAND SUJA DU 😂B3H3NCH0UD K3 DIN3 CH00TIY3 😂K3 BACH3 GAANDV3😂 K3 DIN3 APNI MA K0 CHUDAN3 VAL3 PIL3 SAL3 😂T3RI MAA KI CH00T MAI MIRCHI AUR T3L😂 GARAM KARK3 TADKA LAGA DUNGA😂 T3RI MAA N3 TUJH3 PAIDA KARN3 😂S3 P3HL3 T3R3 😂BAAP KA 1 INCH 😂KA L0WDA L3N3 😂S3 USK0 CH00T 😂KA CANC3R H0 GYA AB😂 MAI D0CT0R BAN K3 T3RI MAA KI😂 CH00T KA ILAAJ 😂KARUNGA",
"T3RI MAA KI 😂CH00T MAI AATANKWADI0 😂S3 NISHAAN3 LAGWAUNGA😂 B3 BH0SDIK3 T3RI MAA KI 😂CH00T MAI GARRAM😂 L0HA DAAL K3 😂JAMA DUNGA H3H33H3H3H3H3H3H3HH 😂T3RI MAA KI CH00T BL0CK 😂H0 JAYGI T3RI B3H3N KI CH00T 😂K0 CHAAQU S3 KAAT KAR😂FIR TAANK3 LAGA KAR 😂 WAPIS P3HL3 JAISA KAR DUNGA 😂T3RI MAA K3 BH0SD3 MAI 😂TUJH3 WAAPIS GHUSS3D DUNGA 😂BAAP S3 FADDA KAR3 GA TU H3IN T3RI😂 MAA KI CH00T MAI GHUSS KAR😂 KHUJLI KARUNGA MAI USS S3 T3RI MAA K0😂 ACHA LAG3GA AB3😂 BH0SDIK3 ",
"T3RI MAA KI😂 CH00T MAI M3THAN3😂 KI PIP3 DAL K3 AAG😂 LAGA DUNGA T3RI MAA 😂R0CK3T KI TARA 😂UD3GI HAHAAHAHAH 😂 SUNA HAI 😂T3RA BAAP CIGRATT3 APNI GAAND😂 S3 P33TA HAY ? Y3 SACH HAI KYA ?😂 AB3 T3RI MAA KI CH00T D3KH 😂JAA K3 ZUNG LAG GYA HAI😂 SAAF T0H KAR LIYA KAR B3H3N 😂K3 L0WD3 SUNA HAI T3RI 😂MAA N3 KISSI AUR S3 😂CHUDWA K3 TUJH3 P3DA 😂KIYA HAY KYUNK3 T3RA BAAP KHUSRA HAI 😂? Y3 SACH HAI KYA ? 😂AB3 T3RI MAA KI NAAK MAI 2😂 M3T3R LAMBI K33L GAAD DUNGA FIR 😂T3RI MAA K0 MUHH S3 SAANS 😂L3NA PAD3GA H33H3H3H3H3 😂ACHA CHAL R00 MAT ACHA Y3 BATA  😂T3RA BAAP BR3AK DANC3 K3R 😂 L3TA HAI KYA SUNA HAI T3RA BAAP 😂 GALI0N MAI L0WDA CH00TA HAI ? Y3 SACH HAI KYA ?😂 SUNA HAI T3RA BAAP KACHRAA UTHAAN3 😂GALI GALI FIRTA HAI Y3😂 SACH HAI KYA ? SUNA HAI T3RI BAAJI BH33K😂 MANG MANG K3 APNI CH00T CHUDWATI 😂HAI ? SUNA HAI T3RI BAAJI CH00T MAI 😂 D00DH DAAL0 T0U",
"TERI MA KO CHODNEE MAZA AATA HAI 🥵"
]
      
